resumeapp/config/routes.rb
Resumeapp::Application.routes.draw do
  get "job/add"

  get "job/list"

  resources :resumes do
    member do
      get 'viewed'
    end
  end

end

resumeapp/app/models/job.rb
class Job < ActiveRecord::Base
  attr_accessible :company_name, :end_date, :start_date, :work_summary
end

resumeapp/app/models/resume.rb
class Resume < ActiveRecord::Base
  attr_accessible :city, :email, :name, :phone, :state, :street, :summary, :zip

  has_many :view_histories
end

resumeapp/app/models/view_history.rb
class ViewHistory < ActiveRecord::Base
  attr_accessible :ip, :resume_id, :time_viewed
end

resumeapp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

resumeapp/app/controllers/job_controller.rb
class JobController < ApplicationController
  def add
  end

  def list
  end
end

resumeapp/app/controllers/resumes_controller.rb
class ResumesController < ApplicationController
  before_filter :prohibit_view

  def prohibit_view
    render :text => "Not authorized", :status => 403 if params[:id] && params[:id].to_i > 200
  end

  def viewed
    resume = Resume.find(params[:id])
    @views = resume.view_histories
  end

  # GET /resumes
  # GET /resumes.json
  def index
    @resumes = Resume.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @resumes }
    end
  end

  # GET /resumes/1
  # GET /resumes/1.json
  def show
    @resume = Resume.find(params[:id])

    vh = ViewHistory.new(:time_viewed => Time.new, :ip => request.remote_ip, :resume_id => @resume.id)
    vh.save

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @resume }
    end
  end

  # GET /resumes/new
  # GET /resumes/new.json
  def new
    @resume = Resume.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @resume }
    end
  end

  # GET /resumes/1/edit
  def edit
    @resume = Resume.find(params[:id])
  end

  # POST /resumes
  # POST /resumes.json
  def create
    @resume = Resume.new(params[:resume])

    respond_to do |format|
      if @resume.save
        format.html { redirect_to @resume, notice: 'Resume was successfully created.' }
        format.json { render json: @resume, status: :created, location: @resume }
      else
        format.html { render action: "new" }
        format.json { render json: @resume.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /resumes/1
  # PUT /resumes/1.json
  def update
    @resume = Resume.find(params[:id])

    respond_to do |format|
      if @resume.update_attributes(params[:resume])
        format.html { redirect_to @resume, notice: 'Resume was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @resume.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /resumes/1
  # DELETE /resumes/1.json
  def destroy
    @resume = Resume.find(params[:id])
    @resume.destroy

    respond_to do |format|
      format.html { redirect_to resumes_url }
      format.json { head :no_content }
    end
  end
end

resumeapp/app/helpers/application_helper.rb
module ApplicationHelper
end

resumeapp/app/helpers/job_helper.rb
module JobHelper
end

resumeapp/app/helpers/resumes_helper.rb
module ResumesHelper
end

resumeapp/app/views/job/add.html.erb
<h1>Job#add</h1>
<p>Find me in app/views/job/add.html.erb</p>

resumeapp/app/views/job/list.html.erb
<h1>Job#list</h1>
<p>Find me in app/views/job/list.html.erb</p>

resumeapp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Resumeapp</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

resumeapp/app/views/resumes/_form.html.erb
<%= form_for(@resume) do |f| %>
  <% if @resume.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@resume.errors.count, "error") %> prohibited this resume from being saved:</h2>

      <ul>
      <% @resume.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :phone %><br />
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :street %><br />
    <%= f.text_field :street %>
  </div>
  <div class="field">
    <%= f.label :city %><br />
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :state %><br />
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :zip %><br />
    <%= f.number_field :zip %>
  </div>
  <div class="field">
    <%= f.label :summary %><br />
    <%= f.text_area :summary %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

resumeapp/app/views/resumes/edit.html.erb
<h1>Editing resume</h1>

<%= render 'form' %>

<%= link_to 'Show', @resume %> |
<%= link_to 'Back', resumes_path %>

resumeapp/app/views/resumes/index.html.erb
<h1>Listing resumes</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Phone</th>
    <th>Email</th>
    <th>Street</th>
    <th>City</th>
    <th>State</th>
    <th>Zip</th>
    <th>Summary</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @resumes.each do |resume| %>
  <tr>
    <td><%= resume.name %></td>
    <td><%= resume.phone %></td>
    <td><%= resume.email %></td>
    <td><%= resume.street %></td>
    <td><%= resume.city %></td>
    <td><%= resume.state %></td>
    <td><%= resume.zip %></td>
    <td><%= resume.summary %></td>
    <td><%= link_to 'Show', resume %></td>
    <td><%= link_to 'Edit', edit_resume_path(resume) %></td>
    <td><%= link_to 'Destroy', resume, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Resume', new_resume_path %>

resumeapp/app/views/resumes/new.html.erb
<h1>New resume</h1>

<%= render 'form' %>

<%= link_to 'Back', resumes_path %>

resumeapp/app/views/resumes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @resume.name %>
</p>

<p>
  <b>Phone:</b>
  <%= @resume.phone %>
</p>

<p>
  <b>Email:</b>
  <%= @resume.email %>
</p>

<p>
  <b>Street:</b>
  <%= @resume.street %>
</p>

<p>
  <b>City:</b>
  <%= @resume.city %>
</p>

<p>
  <b>State:</b>
  <%= @resume.state %>
</p>

<p>
  <b>Zip:</b>
  <%= @resume.zip %>
</p>

<p>
  <b>Summary:</b>
  <%= @resume.summary %>
</p>


<%= link_to 'Edit', edit_resume_path(@resume) %> |
<%= link_to 'Back', resumes_path %>

resumeapp/app/views/resumes/viewed.html.erb
<h1>Listing views</h1>

<table>
  <tr>
    <th>Date</th>
    <th>IP</th>
  </tr>

<% @views.each do |view| %>
  <tr>
    <td><%= view.time_viewed %></td>
    <td><%= view.ip %></td>
  </tr>
<% end %>
</table>